name: build_and_publish_nuget
on: workflow_dispatch
  
jobs:

  build_and_publish_nuget:

    runs-on: windows-latest 
    
    permissions:
      repository-projects: write
      packages: write
      contents: write
      
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 6.0.x
        
    - name: Version
      id: version
      uses: mavrosxristoforos/get-xml-info@1.1.1
      with: 
        xml-file: 'PowerCollections/PowerCollections.csproj'
        xpath: '//Version'
        
    - name: Pack Package
      run: dotnet pack --configuration Release
      
    - name: Push Package
      run: dotnet nuget push "ShadrinaArina.PowerCollections.${{ steps.version.outputs.info }}.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s "https://nuget.pkg.github.com/ShadrinaArina/index.json" 
      working-directory: PowerCollections\bin\Release\
      
    - name: Create Release 
      uses: ncipollo/release-action@v1.12.0
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: 'PowerCollections\bin\Release\*${{ steps.version.outputs.info }}.nupkg'
        tag: ${{ steps.version.outputs.info }}
